// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyAOwELuJCfYy1RGCXoJ3xJWpHa335eNs',
    appId: '1:1015857607546:web:37e8f2af1fc7229f459cc3',
    messagingSenderId: '1015857607546',
    projectId: 'melio-project',
    authDomain: 'melio-project.firebaseapp.com',
    storageBucket: 'melio-project.firebasestorage.app',
    measurementId: 'G-93K52Q6FFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC94WSiCFRBTb52EFgybVxZTGIscucGtGk',
    appId: '1:1015857607546:android:7e18ee27737d40b9459cc3',
    messagingSenderId: '1015857607546',
    projectId: 'melio-project',
    storageBucket: 'melio-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaDYIFCw1dL1fKo7PHfEgKak9e_V6I-Ek',
    appId: '1:1015857607546:ios:d1e8c47e51a4c80a459cc3',
    messagingSenderId: '1015857607546',
    projectId: 'melio-project',
    storageBucket: 'melio-project.firebasestorage.app',
    iosBundleId: 'com.example.melioProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaDYIFCw1dL1fKo7PHfEgKak9e_V6I-Ek',
    appId: '1:1015857607546:ios:d1e8c47e51a4c80a459cc3',
    messagingSenderId: '1015857607546',
    projectId: 'melio-project',
    storageBucket: 'melio-project.firebasestorage.app',
    iosBundleId: 'com.example.melioProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyAOwELuJCfYy1RGCXoJ3xJWpHa335eNs',
    appId: '1:1015857607546:web:bcd4c91ff6d73a9d459cc3',
    messagingSenderId: '1015857607546',
    projectId: 'melio-project',
    authDomain: 'melio-project.firebaseapp.com',
    storageBucket: 'melio-project.firebasestorage.app',
    measurementId: 'G-1254D19QJY',
  );
}
