// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FLUTTERFIRE_WEB_API_KEY'),
    appId: const String.fromEnvironment('FLUTTERFIRE_WEB_APP_ID'),
    messagingSenderId: '1015857607546',
    projectId: 'melio-project',
    authDomain: const String.fromEnvironment('FLUTTERFIRE_WEB_AUTHORS_DOMAIN'),
    storageBucket: 'melio-project.firebasestorage.app',
    measurementId: 'G-93K52Q6FFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FLUTTERFIRE_ANDROID_API_KEY'),
    appId: const String.fromEnvironment('FLUTTERFIRE_ANDROID_APP_ID'),
    messagingSenderId: '1015857607546',
    projectId: 'melio-project',
    storageBucket: 'melio-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FLUTTERFIRE_IOS_API_KEY'),
    appId: const String.fromEnvironment('FLUTTERFIRE_IOS_APP_ID'),
    messagingSenderId: '1015857607546',
    projectId: 'melio-project',
    storageBucket: 'melio-project.firebasestorage.app',
    iosBundleId: 'com.example.melioProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('FLUTTERFIRE_MACOS_API_KEY'),
    appId: const String.fromEnvironment('FLUTTERFIRE_MACOS_APP_ID'),
    messagingSenderId: '1015857607546',
    projectId: 'melio-project',
    storageBucket: 'melio-project.firebasestorage.app',
    iosBundleId: 'com.example.melioProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('FLUTTERFIRE_WINDOWS_API_KEY'),
    appId: const String.fromEnvironment('FLUTTERFIRE_WINDOWS_APP_ID'),
    messagingSenderId: '1015857607546',
    projectId: 'melio-project',
    authDomain: const String.fromEnvironment('FLUTTERFIRE_WINDOWS_AUTHORS_DOMAIN'),
    storageBucket: 'melio-project.firebasestorage.app',
    measurementId: 'G-1254D19QJY',
  );
}
